		<footer>
			<div class="LinkImageBox">
				<img src="images/chibit.png" class="chibit">
				<a href="https://job.rikunabi.com/2019/company/r934220069/" target="_blank"><img src="images/rn_logo_b.gif" class="ricNaviImage"></a>
				<img src="images/qr20180316101758793.png" class="LinkricNaviImageRespons">
			</div>
			<div class="clear"><div>
			<div class="footerMenuBox">
				<ul class="footerMenu">
					<li class="footerMenu"><a href="outline.php" class="footerMenuLink">会社概要<a/></li>
					<li class="footerMenu"><a href="working.php" class="footerMenuLink">仕事内容<a/></li>
					<li class="footerMenu"><a href="phlosophy.php" class="footerMenuLink">経営理念<a/></li>
					<li class="footerMenu"><a href="produce.php" class="footerMenuLink">社員紹介<a/></li>
					<li class="footerMenu"><a href="walfara.php" class="footerMenuLink">福利厚生<a/></li>
					<li class="footerMenu"><a href="recruit.php" class="footerMenuLink">募集要項<a/></li>
					<li class="footerMenu"><a href="https://ja-jp.facebook.com/bit.Japan/" class="footerMenuLink" target="_blank"><img src="./images/fb.png"><a/></li>
					<li class="footerMenu"><a href="https://ameblo.jp/bit-noma/" class="footerMenuLink" target="_blank"><img src="./images/ab.png"><a/></li>
				</ul>
			</div>
			<div class="clear"><div>
			<p class="copyright">Copyright ©2018 BIT Ltd. All Rights Reserved.</p>
		</footer>
