		<header>
			<nav id="menu-box">
			<div id="toggle"><a href="#" class="toggleMenu"><img src="images/rogo.png" class="toggleRogo">RECRUIT MENU</a></div>
				<ul class="menu">
					<li class="menuRogo"><a href="index.html"><img src="images/rogo.png" class="rogo"></a></li>
					<li class="menuHome"><a href="index.html">ホーム!</a></li>
					<li class="menuList"><a href="outline.php">会社概要<span class="menuLinkUnder">Company</span></a></li>
					<li class="menuList"><a href="working.php">仕事内容<span class="menuLinkUnder">Work</span></a></li>
					<li class="menuList"><a href="philosophy.php">経営理念<span class="menuLinkUnder">Vision</span></a></li>
					<li class="menuList"><a href="produce.php">社員紹介<span class="menuLinkUnder">Produce</span></a></li>
					<li class="menuList"><a href="walfara.php">福利厚生<span class="menuLinkUnder">Welfare</span></a></li>
					<li class="menuList"><a href="recruit.php">募集要項<span class="menuLinkUnder">Recruit</span></a></li>
				</ul>
			</nav>
		<div class="clear"></div>
		</header>
